export {
    client,
    getGetCategories as getCategories,
    getGetComments as getComments,
    getGetCurrencies as getCurrencies,
    getGetCurrentUser as getCurrentUser,
    getGetExpenseById as getExpenseById,
    getGetExpenses as getExpenses,
    getGetFriendById as getFriendById,
    getGetFriends as getFriends,
    getGetGroupById as getGroupById,
    getGetGroups as getGroups,
    getGetNotifications as getNotifications,
    getGetUserById as getUserById,
    postAddUserToGroup as addUserToGroup,
    postCreateComment as createComment,
    postCreateExpense as createExpense,
    postCreateGroup as createGroup,
    postCreateFriend as createFriend,
    postCreateFriends as createFriends,
    postDeleteCommentById as deleteCommentById,
    postDeleteExpenseById as deleteExpenseById,
    postDeleteFriendById as deleteFriendById,
    postDeleteGroupById as deleteGroupById,
    postRemoveUserFromGroup as removeUserFromGroup,
    postUndeleteExpenseById as undeleteExpenseById,
    postUndeleteGroupById as undeleteGroupById,
    postUpdateExpenseById as updateExpenseById,
    postUpdateUserById as updateUserById,
} from './sdk.gen';
export * from './types.gen';